# ============================================================================
# Web Crawling Configuration - Configurazione dedicata per crawler Trafilatura
# ============================================================================
#
# IMPORTANTE: Domini sono definiti SOLO in domains.yaml
# Questo file gestisce:
# - Configurazione link crawling e discovery pages
# - Mappatura domini → siti (come web_scraping.yaml)
# - Parametri tecnici crawler e estrazione
# - I domini devono essere attivi in domains.yaml per essere processati
#

# Configurazione generale crawler
general:
  # Rate limiting e performance
  rate_limit_delay: 2.0          # Delay tra richieste (secondi)
  timeout: 15                    # Timeout richieste HTTP (secondi)
  max_retries: 3                 # Numero massimo retry per richiesta
  max_concurrent_requests: 5     # Richieste concorrenti massime
  
  # Limiti contenuto
  max_links_per_site: 25         # Link massimi per sito per sessione
  max_content_length: 50000      # Lunghezza massima contenuto (caratteri)
  min_content_length: 200        # Lunghezza minima contenuto (caratteri)
  
  # Qualità contenuto
  min_quality_score: 0.3         # Score minimo qualità Trafilatura
  extract_metadata: true         # Estrai metadati (autore, data, etc.)
  extract_keywords: true         # Estrai keywords automatiche
  
  # Comportamento crawler
  respect_robots_txt: true       # Rispetta robots.txt
  follow_redirects: true         # Segui redirect HTTP
  verify_ssl: true               # Verifica certificati SSL
  
  # Storage e deduplicazione
  enable_deduplication: true     # Evita duplicati per URL e contenuto
  store_failed_attempts: true    # Salva tentativi falliti per debug
  cleanup_old_links: true        # Pulizia automatica link obsoleti

# Headers HTTP per crawling
headers:
  User-Agent: "Mozilla/5.0 (compatible; TaneaCrawler/2.0; +https://tanea.news/bot)"
  Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
  Accept-Language: "it-IT,it;q=0.9,en;q=0.8"
  Accept-Encoding: "gzip, deflate, br"
  DNT: "1"
  Connection: "keep-alive"
  Cache-Control: "max-age=0"

# === CONFIGURAZIONE LINK CRAWLING ===
# Siti e link organizzati per dominio con parametri specifici
crawling_sites:

  # ========================================================================
  # DOMINIO: CALCIO
  # ========================================================================
  calcio:
    priority: 1                   # Priorità dominio per crawling
    max_articles_per_domain: 100  # Limite articoli per sessione dominio
    
    sites:
      # === GAZZETTA DELLO SPORT ===
      gazzetta:
        name: "Gazzetta dello Sport"
        base_url: "https://www.gazzetta.it"
        active: false             # Sito disattivato per crawling
        priority: 1               # Priorità sito
        rate_limit_override: 1.8  # Override rate limit specifico

      # === CORRIERE DELLO SPORT ===
      corriere_sport:
        name: "Corriere dello Sport"
        base_url: "https://www.corrieredellosport.it"
        active: false
        priority: 2

      # === TUTTOMERCATOWEB ===
      tuttomercatoweb:
        name: "TuttoMercatoWeb"
        base_url: "https://www.tuttomercatoweb.com"
        active: true
        priority: 3
        rate_limit_override: 2.5  # Sito più lento


      # === CALCIOMERCATO ===
      calciomercato:
        name: "Calciomercato"
        base_url: "https://www.calciomercato.com/notizie"
        active: true
        priority: 3
        rate_limit_override: 2.5  # Sito più lento

        

  # ========================================================================
  # DOMINIO: TECNOLOGIA  
  # ========================================================================
  tecnologia:
    priority: 2
    max_articles_per_domain: 50
    
    sites:
      # === ANSA TECNOLOGIA ===
      ansa_tech:
        name: "ANSA Tecnologia"
        base_url: "https://www.ansa.it"
        active: false             # Sito inattivo
        priority: 1

  # ========================================================================
  # DOMINIO: FINANZA
  # ========================================================================
  finanza:
    priority: 3
    max_articles_per_domain: 30
    
    sites:
      # === IL SOLE 24 ORE ===
      sole24ore:
        name: "Il Sole 24 ORE"
        base_url: "https://www.ilsole24ore.com"
        active: false
        priority: 1

# === MAPPATURA DOMINI ===
# Mapping esplicito per validazione e coordinamento
domain_mapping:
  calcio:
    sites: ["gazzetta", "corriere_sport", "tuttomercatoweb"]
    crawling_keywords: ["calcio", "Serie A", "Champions League", "calciomercato"]  # Per filtri crawler
    
  tecnologia:
    sites: ["ansa_tech"]
    crawling_keywords: ["tecnologia", "AI", "software", "hardware"]
    
  finanza:
    sites: ["sole24ore"]
    crawling_keywords: ["finanza", "borsa", "economia", "mercati"]

# === CONFIGURAZIONE AVANZATA ===
advanced:
  # Machine Learning e AI
  use_ai_content_classification: true   # Usa AI per classificare contenuto
  auto_keyword_extraction: true         # Estrazione automatica keywords
  content_similarity_threshold: 0.85    # Soglia similarità per duplicati
  
  # Monitoring e logging
  enable_performance_monitoring: true   # Monitoring performance
  log_failed_extractions: true         # Log estrazioni fallite
  save_extraction_samples: false       # Salva campioni per debug
  
  # Ottimizzazioni
  use_connection_pooling: true          # Pool connessioni HTTP
  enable_compression: true              # Compressione response
  cache_dns_lookups: true              # Cache DNS
  
  # Sicurezza
  validate_content_type: true          # Valida content-type HTML
  check_content_language: true         # Verifica lingua contenuto
  max_redirect_hops: 5                 # Massimi redirect da seguire